syntax = "proto3";

package mmo.public_api;

import "common/context.proto";
import "common/types.proto";

message EnterInstanceRequest {
  mmo.common.RequestContext context = 1;
  int32 dungeon_id = 2;
}

message EnterInstanceResponse {
  mmo.common.ResponseContext context = 1;
  int64 instance_id = 2;
  int64 boss_entity_id = 3;
}

message SettleInstanceRequest {
  mmo.common.RequestContext context = 1;
  int64 instance_id = 2;
  string idempotency_key = 3;
  bool win = 4;
}

message SettleInstanceResponse {
  mmo.common.ResponseContext context = 1;
  string reward_grant_id = 2;
  repeated mmo.common.Reward rewards = 3;
  bool duplicate = 4;
}
