syntax = "proto3";

package mmo.cs;

import "common/error.proto";
import "common/types.proto";

message EnterSceneRequest {
  mmo.common.SceneRoute route = 2;
}

message EnterSceneResponse {
  mmo.common.Result result = 1;
  int64 entity_id = 2;
  mmo.common.Position position = 3;
}

message MoveCommand {
  int64 entity_id = 2;
  mmo.common.Position from = 3;
  mmo.common.Position to = 4;
  int64 client_time_ms = 5;
}

message MoveResult {
  mmo.common.Result result = 1;
  int64 entity_id = 2;
  mmo.common.Position accepted_position = 3;
}
